apiVersion: v1
kind: Service
metadata:
  name: redsphere-service
  namespace: red-sphere
spec:
  type: NodePort
  selector:
    app: redsphere
  ports:
  - protocol: TCP
    port: 4071
    targetPort: 4071
    nodePort: 30312