apiVersion: apps/v1
kind: Deployment
metadata:
  name: redsphere-deployment
  namespace: red-sphere
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redsphere
  template:
    metadata:
      labels:
        app: redsphere
        appVersion: '57ac6b1397077af43ee75c9e69bebc611778234e'
    spec:
      containers:
      - name: redsphere-container
        image: kaributechsworkflow/red-sphere-bk:57ac6b1397077af43ee75c9e69bebc611778234e
        ports:
        - containerPort: 4071