apiVersion: apps/v1
kind: Deployment
metadata:
  name: redsphere-deployment
  namespace: red-sphere
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redsphere
  template:
    metadata:
      labels:
        app: redsphere
        appVersion: '265197bf4df40a7cb15fcc73a63d1f79d0cf1205'
    spec:
      containers:
      - name: redsphere-container
        image: kaributechsworkflow/red-sphere-bk:265197bf4df40a7cb15fcc73a63d1f79d0cf1205
        ports:
        - containerPort: 4071